INSERT INTO products (
  name, price, original_price, category, brand, material, badge, 
  img, images, description, rating, num_reviews, stock, specs, 
  colors, sizes, delivery_days, seller_id
) VALUES 
('Men Solid Polo Neck Cotton Blend T-Shirt', 499, 999, 'Men''s Fashion', 'Allen Solly', 'Cotton Blend', 'TRENDING', 'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/p/s/c/m-auspn0164-allen-solly-original-imagg3ffzhhhzzgq.jpeg', '{"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/p/s/c/m-auspn0164-allen-solly-original-imagg3ffzhhhzzgq.jpeg"}', 'Men Solid Polo Neck Cotton Blend T-Shirt', 4.5, 120, 50, '{"fit":"Slim"}', '{"Black", "Blue"}', '{"S", "M", "L", "XL"}', 3, 'a1a2a91d-e9e7-48bb-95b0-ba0ed2e5deba'),
('Men Solid Round Neck Cotton Blend T-Shirt', 799, 1999, 'Men''s Fashion', 'Puma', 'Cotton Blend', 'BEST SELLER', 'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/t/g/g/m-84722601-puma-original-imaghffnffgfz28b.jpeg', '{"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/t/g/g/m-84722601-puma-original-imaghffnffgfz28b.jpeg"}', 'Men Solid Round Neck Cotton Blend T-Shirt', 4.8, 300, 100, '{"fit":"Regular"}', '{"White", "Black"}', '{"M", "L", "XL"}', 2, 'a1a2a91d-e9e7-48bb-95b0-ba0ed2e5deba'),
('Women Printed Round Neck Pure Cotton T-Shirt', 599, 1299, 'Women''s Fashion', 'Biba', 'Pure Cotton', 'NEW ARRIVAL', 'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/s/j/x/l-5721-6-fastcolors-original-imafvfzyf8pznqzb.jpeg', '{"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/s/j/x/l-5721-6-fastcolors-original-imafvfzyf8pznqzb.jpeg"}', 'Women Printed Round Neck Pure Cotton T-Shirt', 4.2, 50, 200, '{"fit":"Regular"}', '{"Red", "Yellow"}', '{"S", "M", "L"}', 4, 'a1a2a91d-e9e7-48bb-95b0-ba0ed2e5deba'),
('Women Solid Round Neck Pure Cotton T-Shirt', 499, 999, 'Women''s Fashion', 'Biba', 'Pure Cotton', 'TRENDING', 'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/8/y/n/m-wstshrt-1011-fastcolors-original-imaghfzztgffzp5f.jpeg', '{"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/8/y/n/m-wstshrt-1011-fastcolors-original-imaghfzztgffzp5f.jpeg"}', 'Women Solid Round Neck Pure Cotton T-Shirt', 4.6, 210, 80, '{"fit":"Slim"}', '{"Pink", "White"}', '{"XS", "S", "M"}', 3, 'a1a2a91d-e9e7-48bb-95b0-ba0ed2e5deba'),
('Women Printed Round Neck Pure Cotton T-Shirt (Combo)', 399, 899, 'Women''s Fashion', 'Biba', 'Pure Cotton', 'BEST SELLER', 'https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/d/e/v/m-wstshrt-1002-fastcolors-original-imaghfzzqffhgzhv.jpeg', '{"https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/d/e/v/m-wstshrt-1002-fastcolors-original-imaghfzzqffhgzhv.jpeg"}', 'Women Printed Round Neck Pure Cotton T-Shirt Combo Pack', 4.9, 500, 300, '{"fit":"Regular"}', '{"Multicolor"}', '{"S", "M", "L", "XL"}', 2, 'a1a2a91d-e9e7-48bb-95b0-ba0ed2e5deba');
